# This installs OpenSCAP, SCAP content, and prepares the server to run local/remote scans. In addition,
# the script deploys Apache webserver to host the latest scans here: "http://test-openscap-server/openscap/latest.html" 
#
# Optional timestamped history: http://test-openscap-server/openscap/report_2025-07-31_14:02:11.html
---
- name: Install and configure OpenSCAP report server
  hosts: openscap
  become: true

  vars:
    web_report_dir: /var/www/html/openscap

  tasks:
    - name: Install required packages for OpenSCAP scanning
      dnf:
        name:
          - openscap-scanner
          - scap-security-guide
        state: present

    - name: Install Apache to serve HTML reports
      dnf:
        name: httpd
        state: present

    - name: Ensure Apache is started and enabled
      systemd:
        name: httpd
        enabled: yes
        state: started

    - name: Create OpenSCAP web report directory
      file:
        path: "{{ web_report_dir }}"
        state: directory
        mode: '0755'

    - name: Add placeholder index file
      copy:
        content: |
          <html>
          <head><title>OpenSCAP Reports</title></head>
          <body>
            <h1>No reports found.</h1>
            <p>Use scan playbooks to generate reports here.</p>
          </body>
          </html>
        dest: "{{ web_report_dir }}/latest.html"
        mode: '0644'

    - name: Debug message for user access
      debug:
        msg: |
          OpenSCAP report server is ready.
          Upload scan reports to: {{ web_report_dir }}
          Access them at: http://{{ inventory_hostname }}/openscap/latest.html
