---
- name: Deploy OpenVAS Scanner and Schedule Daily Scans
  hosts: test-openvas-server
  become: true

  vars:
    report_dir: /home/test-openvas-server/reports
    report_retention_days: 7
    scan_target: "10.5.5.0/24"
    scan_target_id: "REPLACE_WITH_TARGET_UUID"
    full_scan_id: "REPLACE_WITH_FULL_SCAN_UUID"
    xml_format_id: "REPLACE_WITH_XML_FORMAT_UUID"
    html_format_id: "REPLACE_WITH_HTML_FORMAT_UUID"

  tasks:
    - name: Install OpenVAS and dependencies
      apt:
        name:
          - openvas
          - gvm
          - python3-lxml
          - jq
          - rsync
        state: present
        update_cache: yes

    - name: Run GVM setup
      command: gvm-setup
      args:
        creates: /var/lib/gvm/.notus/ntp/
      register: gvm_setup
      changed_when: gvm_setup.rc == 0

    - name: Create reports directory
      file:
        path: "{{ report_dir }}"
        state: directory
        owner: gvm
        group: gvm
        mode: '0755'

    - name: Deploy scan script
      copy:
        dest: /usr/local/bin/run_openvas_scan.sh
        content: |
          #!/bin/bash
          UUID=$(gvm-cli --gmp-username admin --gmp-password admin_password --xml "<create_task><name>Scheduled Scan</name><config id='{{ full_scan_id }}'/><target id='{{ scan_target_id }}'/></create_task>" | xmllint --xpath 'string(//create_task_response/@id)' -)
          gvm-cli --gmp-username admin --gmp-password admin_password --xml "<start_task task_id='${UUID}'/>"
          sleep 180
          REPORT_ID=$(gvm-cli --gmp-username admin --gmp-password admin_password --xml "<get_reports filter='rows=1 sort-reverse=1'/>" | xmllint --xpath 'string(//report/@id)' -)
          gvm-cli --gmp-username admin --gmp-password admin_password --xml "<get_report report_id='${REPORT_ID}' format_id='{{ xml_format_id }}'/>" > {{ report_dir }}/report-$(date +%F-%H%M).xml
          gvm-cli --gmp-username admin --gmp-password admin_password --xml "<get_report report_id='${REPORT_ID}' format_id='{{ html_format_id }}'/>" > {{ report_dir }}/report-$(date +%F-%H%M).html
          find {{ report_dir }} -type f -mtime +{{ report_retention_days }} -delete
        mode: '0755'
        owner: root
        group: root

    - name: Install cronjob for scan execution
      cron:
        name: "Daily OpenVAS Scan"
        user: gvm
        job: "/usr/local/bin/run_openvas_scan.sh"
        minute: "0"
        hour: "9"
