---
- name: Add OpenVAS user to Linux systems with correct admin group
  hosts: all
  become: true
  gather_facts: true
  vars:
    username: openvas
    user_password: "0526"
  tasks:
    - name: Determine admin group name
      set_fact:
        admin_group: "{{ 'sudo' if ansible_facts.os_family == 'Debian' else 'wheel' }}"

    - name: Ensure admin group exists
      group:
        name: "{{ admin_group }}"
        state: present

    - name: Create user with home dir and password
      user:
        name: "{{ username }}"
        password: "{{ user_password | password_hash('sha512') }}"
        state: present
        create_home: yes
        shell: /bin/bash

    - name: Add user to admin group
      user:
        name: "{{ username }}"
        groups: "{{ admin_group }}"
        append: yes

    - name: Ensure home directory permissions
      file:
        path: "/home/{{ username }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'
