---
- name: Ensure OpenVAS user exists on all target Linux VMs
  hosts: all  # Define target hosts in your Semaphore inventory
  become: true
  vars:
    username: "openvas"         # Set desired username
    user_password: "0526"    # Set desired password (plaintext, hashed below)

  tasks:
    - name: Create user with home directory and hashed password
      user:
        name: "{{ username }}"
        password: "{{ user_password | password_hash('sha512') }}"
        state: present
        create_home: yes
        shell: /bin/bash
        update_password: on_create

    - name: Add user to sudo group
      user:
        name: "{{ username }}"
        groups: sudo
        append: yes

    - name: Ensure home directory permissions are correct
      file:
        path: "/home/{{ username }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'
