# Update username and password vars then execute script to create user
#
---
- name: Add user to Linux VM servers
  hosts: all #UPDATE INVENTORY FILE
  become: true
  vars:
    username: "openvas" #UPDATE USER
    user_password: "openvas" #UPDATE PASSWORD
  tasks:
    - name: Ensure the user exists
      user:
        name: "{{ username }}"
        password: "{{ user_password | password_hash('sha512') }}"  # Password is hashed using SHA-512.
        state: present
        create_home: yes
        shell: /bin/bash
        update_password: on_create

    - name: Add user to sudo group (optional)
      user:
        name: "{{ username }}"
        groups: sudo
        append: yes

    - name: Create home directory (if not created automatically)
      file:
        path: "/home/{{ username }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'
